peazip actions: add peazip actions (extract, compress) to the contextual menu, new spice
linuxmint/cinnamon-spices-actions pull request #144
Opened 2024-01-21 19:22 UTC by BlancoBv

I create this new spice to add peazip extract and compress option in nemo.

2024-01-21 19:53 UTC, rcalixte requested changes

2024-01-21 19:53 UTC, rcalixte commented on peazip-actions@BlancoBv/files/peazip-actions@BlancoBv/metadata.json
> +    "uuid": "peazip-actions@100savage",
This is incorrect. (It should have failed validation so I'll look into that separately.)

2024-01-21 19:53 UTC, rcalixte commented on peazip-actions@BlancoBv/peazip_add.nemo_action.in
> +
There can only be one Action per uuid and the name needs to match the uuid.

2024-01-21 19:53 UTC, rcalixte commented on peazip-actions@BlancoBv/peazip_extract_here.nemo_action.in
> +
Same here.

2024-01-21 19:53 UTC, rcalixte commented on peazip-actions@BlancoBv/peazip_extract_to.nemo_action.in
> +
And here.

2024-01-21 19:55 UTC, rcalixte commented
You can test validation on your local branch by running `./validate-spice peazip-actions@BlancoBv` in the root directory. You can run `./validate-spice -h` for more details or read the README as well. Feel free to shout if you have any questions!

2024-01-21 20:04 UTC, rcalixte commented
The validation bug has been fixed. Please make sure to pull the latest changes to the branch on your fork.

2024-01-21 22:42 UTC, BlancoBv commented
I'v  change the name to peazip-extract-here and use the validate-spice script, all seems to look fine.

2024-01-21 23:04 UTC, rcalixte approved these changes

2024-01-21 23:04 UTC, rcalixte commented
> I'v change the name to peazip-extract-here and use the validate-spice script, all seems to look fine.

Looks good. Feel free to open pull requests for the other two and we'll get them merged for you!

2024-01-21 23:05 UTC, merged

2024-01-22 00:37 UTC, claudiux commented on peazip-extract-here@BlancoBv/peazip-extract-here@BlancoBv.nemo_action.in
Maybe add a line `Dependencies=peazip` ? Or `Dependencies=io.github.peazip.PeaZip` ? What do you think about it @rcalixte @BlancoBv  ? This is a flatpak (flathub) package.

2024-01-22 00:44 UTC, rcalixte commented on peazip-extract-here@BlancoBv/peazip-extract-here@BlancoBv.nemo_action.in
I thought about this as an option. The Flatpak check would only work if the user's path includes it and it might not be there since the path isn't set by default when the flatpak package in installed. It wouldn't hurt to have the package name there but then it would be excluded if the user has the Flatpak installed instead of a local package. Without re-engineering other parts of Nemo, it would be hard for both. Those were my thoughts on why it was okay without.

2024-01-22 00:49 UTC, BlancoBv commented on peazip-extract-here@BlancoBv/peazip-extract-here@BlancoBv.nemo_action.in
Added 
- Dependencies=peazip

2024-01-22 00:55 UTC, rcalixte commented on peazip-extract-here@BlancoBv/peazip-extract-here@BlancoBv.nemo_action.in
> Added
> 
>     * Dependencies=peazip

He means in the action file itself, not the README. There's a tradeoff in the decision to do that though. As it currently is, the context menu will show for anyone who installs this Action, regardless if they have PeaZip installed or not. If you opt to change that Action's structure, there isn't currently a method to support Flatpak users of PeaZip.

My take is that users of PeaZip who want this will install it and others who don't will leave it alone since they don't need it. It's ultimately your call as the author for what you want to do.

2024-01-22 01:03 UTC, BlancoBv commented on peazip-extract-here@BlancoBv/peazip-extract-here@BlancoBv.nemo_action.in
I've already added into the action file, however isn't a bad idea do another spice specifically for the flatpak version.

2024-01-22 03:36 UTC, BlancoBv commented on peazip-extract-here@BlancoBv/peazip-extract-here@BlancoBv.nemo_action.in
Sorry, I didn't sync the changes in my repository